version: 2
workflows:
  version: 2
  build:
    jobs:
      - build-image
jobs:
  build-image:
    docker:
      - image: docker:git
    environment:
      VARNISH_VERSION: 6.5.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build --build-arg VARNISH_VER=${VARNISH_VERSION} -t ${DOCKER_USER}/alpine-varnish:${VARNISH_VERSION}-amd64 .
            docker tag ${DOCKER_USER}/alpine-varnish:${VARNISH_VERSION}-amd64 ${DOCKER_USER}/alpine-varnish:latest
      - run:
          name: upload image to docker hub.
          command: |
            docker login --username=${DOCKER_USER} --password=${DOCKER_PASS}
            docker push ${DOCKER_USER}/alpine-varnish:${VARNISH_VERSION}-amd64
            docker push ${DOCKER_USER}/alpine-varnish:latest
